<?php

/**
 * Implements hook_menu().
 */
function commerce_deposit_menu() {
  $items = array();
  $items['admin/commerce/config/deposit'] = array(
    'title' => 'Deposit settings',
    'description' => 'Configuration for Commerce Deposit module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_deposit_settings_form'),
    'access arguments' => array('configure store'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings form builder.
 */
function commerce_deposit_settings_form($form, &$form_state) {
  $types = commerce_product_types();
  dpm($types);
  $fields = field_info_field_map();
  dpm($fields);
  /*if (!isset($fields[])) {
  }*/
  $form['commerce_deposit'] = array(
    '#markup' => '<p>Hello</p>'
  );
  return system_settings_form($form);
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
/*function commerce_deposit_commerce_line_item_type_info() {
    return array(
        'deposit' => array(
            'name' => t('Deposit'),
            'product' => TRUE,
            'description' => t('Make a deposit for a product.'),
            'add_form_submit_value' => t('Make a Deposit'),
            'base' => 'commerce_product_line_item',
        ),
    );
}*/

/**
 * Implements hook_commerce_line_item_type_info().
 */
function commerce_deposit_commerce_line_item_type_info() {
  $line_item_types = array();
  $line_item_types['deposit'] = array(
    'name' => t('Deposit'),
    'description' => t('Used to make a deposit towards a product.'),
    'product' => FALSE,
    'base' => 'custom_type'
  );
  return $line_item_types;
}

/**
 * Implements hook_enable().
 */
function commerce_deposit_enable() {
  //commerce_product_line_item_configuration(array('type' => 'commerce_deposit'));
  commerce_line_item_configure_line_item_fields(array('commerce_deposit'));
}



/**
 * Implements hook_form_alter().
 */
function commerce_deposit_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form_id); // DEVEL THROWS A WSOD
  //drupal_set_message('<pre>' . print_r($form, true) . '</pre>');
  // If the product allows a deposit, show the deposit button.
  /*if (isset($form['#attributes']['class'][0]) && $form['#attributes']['class'][0] == 'commerce-add-to-cart') {
    $prepopulate = 'edit[field_deposit_course_event][und]=' . $form['line_item_fields']['#entity']->line_item_label;
    $form['deposit'] = array(
      '#type' => 'button',
      '#value' => 'Make a Deposit',
      '#weight' => 999,
      '#attributes' => array(
        'onclick' => 'window.location = "/node/add/deposit?' . $prepopulate . '"; return false;'
      )
    );
    //drupal_set_message('<pre>' . print_r($form, true) . '</pre>');
  }*/
}

